@include('dashboard.layout.header')
@include('dashboard.layout.slide')
@include('dashboard.layout.movie-items')
@include('dashboard.layout.trailers')
@include('dashboard.layout.latestnew')
@include('dashboard.layout.footer')